:PROPERTIES:
:ID:       cdcfcd50-4a4b-457d-815b-bd72ca78f737
:END:
#+title: Reflecting on Jehovah's qualities builds faith
#+filetags: :treasures:

[[id:360543e2-053b-4a88-a7de-10a1868ede25][Treasures from god's word]]


* intro

brothers I would like to ask you to picture your self in Jerusalem months before it was destroy.
the Babylonians have surrounded the city and are besegin it's walls.
food is short and people are exhausted.
Jeremiah was confined to the court yard.

during a time such as this is when Jehovah gives these instructions to Jeremiah.

you cousin Hanmel will come to you saying "Buy my field from Anathoth"


could you imagine what might have been going on in Jeremiah's head?
Does Jehovah really want me to invest in restate in a time like this?
but despite what ever confusion or concerns he may have had, Jeremiah's did what Jehovah instructed him as always

so why did God asked Jeremiah to buy that field?
Jeremiah already had faith that God would allow the Jews to return after 70 years have passed.
but Jehovah is reinforcing that faith by giving him something physical to help him think about the time when
'Houses and fields and vineyards will again be bought in this land'

friends it's never too late for you to buy a field in anothoth.

what am I talking about?

in [[id:843f6124-5bcf-4762-85c3-a6446320b23f][Hebrews_11:1]]
=Faith is the assured expectatio nof what is hope for,..=

in the Simple English bible it says
=Faith is the title deed for good things to come.=

if you think about it our faith is the deed that guarinties that we a special place waiting for us in paradice.

but how do we build our faith so that it's as real to use as holding a physical deed in our hands.

remember A deed is only as good as the ones who signs it.
if the person you entered the agreement with will not honor it then all you have is a piece of paper.

but if you know the person you signed with is not only able but willing to honor their part of the agreement.
then you can literly take that to bank.

in the same way when we reflect on Jehovah's qualities we can begin to see that Jehovah is not just willing
but able to fullfill his part of the agreement.

in this talk we are going to see how reflecting on Jehovah's qualities can build our faith so it's as good as holding deed.
and we are going to do that by focus on three qualities, his powerm, his love and his justice.


* Lets first focus on his Power

tell me if you heard this phrase before, don't let your mouth write checks which you can't cash.

Jehovah has made some pretty large promise.
World Peace,
Restoring the earth into a paradise.
Resurrecting the dead

That's a pretty tall order. do you think god is able to make good on his claims.
let's see what Jeremiah has to say.

[[id:5bbb91b4-878c-4d0b-8b0d-00efb6e4e4d2][Jeremiah 32:17]]

it says here nothing is too wonderful for you.

maybe you more convincing?

if you need physical evidence look further evidence of Jehovah's power look no further than creation.


take For example take the sun.
at it core, it temperature is 27,000,000 F or 15,000,000 C
every second it emits enery equivalent to hundres of million of atomic bombs.

yet our sun is small in comparison to many untold trillions of stars.
scientis estimate that one of the largest starts, named UY Scuti, has a diameter 1,700
times of the sun. If UY Scuti repaced the sun, it would engulf the earth and extend beyond
the orbit of jupiter.

God not only made that but he is aware of the smallest sparrow falling to the ground the biggest super nova exploading.
He is not only aware but also maintains of it.
And he does it with ease.

All of this lighter than a feather to him.

How do we know that.
despite everything that is going on in creation he still has unlimited time to hear our prayers.

it like walking and chewing gum at the time for him.


* Well you might begin to think that sounds pretty impressive.

so some might think so what.

just because he is able doesn't mean he is willing?

fair point.

why would God bother even thinking about us let alone use his power to benefit us?

lets see if Jeremiah can give use a reason

[[id:1d9acea5-be01-4744-9829-f33b4dc902cb][Jeremiah 32:18]]

=the one showing loyal love.=

in the glossary loyal love is
Love motivated by commitment, integrity, loyalty, and deep attachment.

Before we began serving Jehovah, we received the love that God shows to man kind in a general sense.
We received rain, sun, and get to enjoy flowers, plants, animals and trees,
we also received an opportunity to benefit from the ransom.

but He only shows loyal love to those whom he has a special relationship with.

he does not give that to just anyone.

Because he is committed and deeply attach to us because we are exersising Faith in his son.
He will spare no resource and never give up on those he has attached himself with

it's loyal love that move him to forgive us.
it's that loyal love that moves him to protect us.
it's because of his loyal love we can be sure that he will help us


* Jehovah's sense of justice reminds us that he sees injustice and will act against it

some people might begin to worry that because God is so loving, kind and willing to forgive he is just going to allow this world to remain as it is.

again lets see what Jeremiah has to say about that.

[[id:f34576ae-dffc-455a-8c43-0e117289ec41][Jeremiah 32:19]]
=he gives to each one according to his way and according to what he does=

Friends remember this God's love is infinite not his patience.
His patience is vast and incomprehensible to us humans but it does have it's limits.
and Loving God or no loving God be sure of this everyone will reap what they sow.

we might feel like Jeremiah who at times was frustrated at what he perceived as God's delly his justice.
but he never question it.

Because of God's sence of justice we can be sure that on his Day he will do something about the injustice in this word.
It's not a question of if but when.
Be sure of this God's will come.
Nothing stops this train.

* conclusion

so friends, lets take a look at this Illustration.

we see a father pointing to his to God's creation.
he might use nature to help explain God's qualities to his son.
maybe he is explaining god's power to his son.
maybe the using the example of the sky to help illustrate to his son how vast God's love is toward us.
maybe he is using the example of the mountains to show his son how inmovable God's justice is.

the more and more we meditate on his qualities the more we can be certain of his promises for us
it's because of his Power that we know that he is able to cary them out.
it's because of his love that we know that he wants to.
but it's because of his Justice that we know that he will.




* outline

** intro

*** picture your self during the last months of Jerusalem
- besieging it's walls
- food is short and people are exhausted

*** Jehovah give instruction to buy a field
- imagine what Jeremiah might be thinking
- despite what ever confusion or concerns he might have had

*** why did God ask Jeremiah to buy that field?
- Jeremiah already knew that God would allow the jews to return
- but Jehovah reinforced that faith by giving him something physical.
  - to look forward to a time where
    =Houses, fields, and vineyards will again be bought in this land=

*** friends it's never to late for you to buy a field in anothoth 
- what do I mean? in Hebrews 11:1
  =Faith is the assured expectation of what is hope for, ...=

- in the simple english bible it says
  =Faith is the title deed for good things to come.=

- our faith is a deed 

- but how do you build your faith so that it's as real as holding a deed?

- a deed is only as good as the person you signed with.

- but if get to know that the person before you sign anything
  then you know you can take it to the bank.

- when we reflect on God's qualities we can be sure that he will make good
  on his promises for us.

- in this talk we are going to see how reflecting on Jehovah's qualities
  can build our faith in him

- by focusing on three qualites, his power, love and justice.


** Power

don't let your mouth write a check you can't cash

World Peace, Restoring the earth to a paradise, Resurrecting the dead

that's a pretty tall order, do you think Jehovah can make good on his word?

*** Jeremiah 32:17
- it say nothing is too wonderful for you.

*** look at creation
**** take for example the sun.
- every second it emits the enery equivalent to hundreds of millions of atomic bombs
- our sun is small in comparison to many untold trillions of stars.
- UY Scuti, has a estimated diameter of 1,700 times our sun
- if UY Scuti replaced the sun, it would engult the earth and extend to the orbit of jupiter.

*** Can the God who
- create all the starts in the galexie and the earth, not restore
- who gave life to everyone not be able to restore it?
  
** Love
Some might agree with everything I just said

just because he is able doesn't mean he is willing.

Why would God even think about us let alone use his power to benefit us?

*** Jeremiah 32:18

=the one showing loyal love.=

- Loyal love is love motivated by commitment, integrity, loyalty, and deep attachment.

- before we began serving Jehovah, we received the love that god shows to man kind in general
  + rain, sun, plants and the opportunity to receive eternal life

- but now that we entered into a relationship with him by exercising faith in his Son we now revive his loyal love

- that love moves him to forgive us.

- it's his loyal love that moves him to protect us.

- it's because of his loyal love we can be sure that he will help us.


** Justice

But because God is so loving, kind, and willing to forgive,
some might wonder if he will ever carry out true justice in this World.
He is just always going to pardon and let thing slide

*** Jeremiah 32:19
=he gives to each one according to his way and according to what he does=

- God's love is infinite but not his patience.
- His patience is vast and incomprehensible to us humans but it does have it's limits.

  - Jeremiah was at time frustrated at what he perceived as God delaying his justice
    but he never questions it.

  - Because of God's justice be can be sure that his Day will come

  - it's not a question of if but when.

  - nothing stops this train.

** conclusion

lets take a look at the illustration.

- we see a father using creation to explain to his son God's qualities
  - his power,
  - uses the sky to show how vast God's love is
  - mountans how unshakable his justice.

The more and more we meditate on his qualities the more our faith grows.
the more our faith grows the more real parise be comes to us.

- it's because of his power we know he can make it happen
- it's because of his love we know he wants to make it happen
- but it's because of his justice we can be certain that he will.

The more real the paradise becomes to use the more certain we can be that we have a special place waiting for use there.
Enjoy you property in anathoth.
   
