#+title:      tan-stack-router
#+date:       [2026-08-14 Fri 17:20]
#+filetags:   :router:tanstack:
#+identifier: 20260814T172024

define routes once,

file-based routing

the vite plugin compiles the file based router

it uses file base routing, like next.js
routes will mimik folder structure

routeTree.gen.ts : routes are generated and this is what makes it typescript compatible.
acutomatically generated by tanstack router

__root.tsx : our route route, every other route is a child of

you can make a route lazy so that it only get loaded until the app goes to the route



* quick start

setup a completely new project using tanstack-router
#+begin_src bash
  npx @tanstack/cli create --router-only
#+end_src


tanstack router supports both file-based and code-based route configurations.

file-base approach is the recommended option.
it automatically creates routes based on your file structure

if you prefer to define routes programmatically, you can use code-based route configuration.

to install tanstack router to your project
#+begin_src bash
  npm i @tanstack/react-router
#+end_src

* basic route

#+begin_src typescript
  import { createFileRoute } from '@tanstack/react-router'

  export const Route = createFileRoute('/home')({
      component: RouteComponent,
  });

  function RouteComponent() {
      ....
  }
#+end_src

create a link button
#+begin_src typescript
  <Link to="/about" </Link>
#+end_src

navigate programatically
#+begin_src typescript
  const navigate = useNavigate();

  navigate({to: '/about'})
#+end_src

index.tsx in folder, an index route

route.tsx is the layout route
#+begin_src typescript
  import { createFileRoute, Outlet } from '@tanstack/react-router'

  export const Route = createFileRoute('/.../.../')({
      component: RouteComponent,
  })

  function RouteComponent() {
      return <div><Outlet/></div>
  }
#+end_src

dynamic routes
ex: $posts.tsx
it must always start with a dollar sign

#+begin_src typescript
  import { createFileRoute } = from "@/tanstack/react-route"

  export const Route = createFileRoute("/posts/$postId")({
      component: RouteComponent,
  })

  function RouteComponent() {
      const {postId} = Route.useParams();

      const { data } = useQuery({
  	queryKey: ["post", postId],
  	queryFn: () => fetchPosts(postId),
      })
      
      return <div>{JSON.stringify(data)}</div>
  }
#+end_src

loader is what is fetch before route is loaded
#+begin_src typescript
  import { createFileRoute } from "@tanstack/react-router"

  export const Route = createFileRoute("/slowPosts/$postId")({
      loader: ({params}) => fetchSlowPosts(params.postId),
      component: RouteComponent,
  })

  function RouteComponent() {
      const data = Route.useLoaderData()

      return <div>{JSON.stringify(data)}</div>
  }
#+end_src

search params

#+begin_src typescript
  import { createFileRoute } from "@tanstack/react-router"
  import { useState } from "react"
  import { z } from "zod"

  // define schema
  const productSearchSchema = z.object({
      category: z.enum(["all", "running", "casual"]).default("all"),
      brand: z.enum(["all", "Nike", "Adidas", "Converse", ...]).default("all"),
      sortBy: z.enum(["name", "price-asc", ...]).default("name"),
      page: z.number().int().positive().default(1),
  })

  type ProductSearch = z.infer<typeof productSearchSchema>

  export const Route = createFileRoute("/shop")({
      component: RouteComponent,
      validateSearch: productSearchSchema,
  })

  function RouteComponent() {
      const navigate = useNavigate();
      const searchParams = Route.useSearch()

      navigate({ search: (pre) => ({...prev, page: "..."}) })
  }
#+end_src
