:PROPERTIES:
:ID:       e160baba-c47c-4c67-8c31-16061546bb27
:END:
#+title: Loyal Love

Love motivated by commitment, integrity, loyalty, and deep attachment.

Loyal love is a deep everlasting attachment

never miss an opportunity to show love

Loyal love is motivated by commitment, integrity, loyalty, and deep attachment.

What is Loyal Love?
To Whome does Jehovah show loyal love?
How do those who receive it benefit from it?

love motivated by commitment, integrity, loyalty, and deep attachment.

Jehovah is the supreme example of loyal love.

only Jehovah is described as being abundant with loyal love.

Loyal love is never extended to things or ideas; it's shown only to people.
but Jehovah does not show loyal love to just anyone.
He shows it to those who are in a special relationship with him.
God is loyal to his friends.
He has a wonderful purpose for them.
and he will not give up on them.

However Jehovah has shown love to mankind in general.
even those who do not worship him.
he give Sunshine and rain,
Flowers, Plants and trees.
he gives the opportunity to benefit from the ransom.
