What is the meaning to Jeremiah 29:11

* Jeremiah 29:11

I well know the thoughts I have for you, declares Jehovah
thoughts of peace, and not of calamity,
to give you a future and a hope.
=New World Translation=

I know the plans I have for you,’ declares the LORD, ‘plans to prosper you and not to harm you, plans to give you hope and a future.’
=New International Version=

* Effective Introduction

your introduction should arouse interest, identify your subject and show why your listeners should be interested in it

** Arouse Interest
Select a question, real-life experience, or news item that will be of interest to you listeners.

give careful thought to the interests and concerns of you listener

** Identify the subject
make sure your subject and purpose is clear to your listeners

** Show why the subject is important.
they should understand how the subject can help them

* Meaning of Jeremiah 29:11

Jehovah God promised his worshipers that he had a peaceful future in mind for them.

Though written in the past, these words still reflect God's thoughts.

God had these things recorded so that we might have hope.
=Romans 15:4=

* Context of Jeremiah 29:11

These words were part of a letter sent to the Israelites in Babylon,
who were taken captive from Jerusalem. *Jeremiah 29:1*

in *Jeremiah 29:4-9*, he is telling them that they will be there for a long time and that
they should build homes, plant gardens, and raise families.

However lets read,  *Jeremiah 29:10*

it says that after 70 years god would turn his attention to them, and that is when *Jeremiah 29:11* comes in

God kept his promise.

the fulfilled promise of Jeremiah 29:11 assure those who hope in God's promises today.

* Misconception 1: God has a specific plan for each individual

fact God lets people choose for themselves

his words in Jeremiah 29:11 were addressed to a group.

* Misconception 2: God will prosper his worshipers

the word prosper is translated from the hebrew word that mean "peace,health and well-being"

according to the context God promissed his people that he would give them peace and wellfare.

* outline

** Tell me is you have heard this  
god has a plan for you life.
that sounds nice.
but when something goes wrong  does that mean that God planed it?

** A lot of people have the idea that God has a specific plan for every individual
some people receive some comfort from that idea

*** however this idea can cause a lot of misunderstand and frustration when trying to draw close to god
- some people might wonder, if everything that is going to happen to me is already been desided how do I have free will?
- more over if God has a plan than what is the poit to praying to him?
  what do you want him to do? change the plan?

** Where did this idea that God has this plan for everyone come from.
- false religion
- philosophy
- misunderstanding of the scriptures and failing to consider it's context.
  one in particular is Jeremiah 29:11
  In this talk we are going to really look close to what Jeremiah and try to figure out it's real meaning.
  
** Let us read Jeremiah 29:11
- notice how we use the word thoughts
- now i would like to read the new international version of 
 =‘I know the plans I have for you,’ declares the LORD,‘plans to prosper you and not to harm you,
  plans to give you hope and a future.=
  do you see how suttle difference in translation can potentially convey different idea from others?
  so what is the correct interpretation?
   
** but remember this friends, Context matters.

- so lets now read Jeremiah 29:1

  These words were part of a letter sent to the Israelites in Babylon,
  who were taken captive from Jerusalem.

  this letter was adressed to a Group of people, not an individual.

  he is telling them that they will be there for a long time and that
  they should build homes, plant gardens, and raise families.

  However lets look at Jeremiah 29:10.

- let look a Jeremiah 29:10

  now Jeremiah 29:11 is more clearer.
  Jehovah is not saying that he has an individual plan for everyone but that ...

  do you see know how context can completly change the meaning of a scripture.
  it's not that translation from the new international version is wrong but if you dont' consider the context
  that scripture can take on a totaly different meaning.

** Conclusion
I want to be very carful. I'm not saying that God does not think ahead or plan.  No doubt he has good intentions for us and is
looking forward to giving use future blessing in his kingdom.  but He also does not take away our free will.
this was recored not to show that he has a plan for each individual but that he alway comes through with his promises.
after the 70 years were over Jehovah brought his people back as he said he would.
Where else in history is there and example of a people who were ethnicaly cleansed from their homeland
and then less than a generation later allowed to comeback.
If Jehovah came through for those people back then how much more should we expect him to fullfill his Plans for use now.
so when you hear the phrase that God has a plan for your life. we know that is partialy true but we also it up to us if we are
going to go through that plan.
