* Jeremiah 29:11

I well know the thoughts I have for you, declares Jehovah
thoughts of peace, and not of calamity,
to give you a future and a hope.
=New World Translation=

I know the plains I have for you ...
=New International Version=

* Meaning of Jeremiah 29:11

Jehovah God promised his worshipers that he had a peaceful future in mind for them.

Though written in the past, these words still reflect God's thoughts.

God had these things recorded so that we might have hope.
=Romans 15:4=

* Context of Jeremiah 29:11

These words were part of a letter sent to the Israelites in Babylon,
who were taken captive from Jerusalem. *Jeremiah 29:1*

in *Jeremiah 29:4-9*, he is telling them that they will be there for a long time and that
they should build homes, plant gardens, and raise families.

However lets read,  *Jeremiah 29:10*

it says that after 70 years god would turn his attention to them, and that is when *Jeremiah 29:11* comes in

God kept his promise.

the fulfilled promise of Jeremiah 29:11 assure those who hope in God's promises today.

* Misconception 1: God has a specific plan for each individual

fact God lets people choose for themselves

his words in Jeremiah 29:11 were addressed to a group.

* Misconception 2: God will prosper his worshipers

the word prosper is translated from the hebrew word that mean "peace,health and well-being"

according to the context God promissed his people that he would give them peace and wellfare.

* outline
** 
