:PROPERTIES:
:ID:       d6a9fbf9-ba02-4697-834a-e8b90c6ac9f8
:END:
#+title: What is the meaning to Jeremiah 29:11
#+filetags: :jeremiah-29_11:talk:

What is the meaning to Jeremiah 29:11

* Jeremiah 29:11

I well know the thoughts I have for you, declares Jehovah
thoughts of peace, and not of calamity,
to give you a future and a hope.
=New World Translation=

I know the plans I have for you,’ declares the LORD, ‘plans to prosper you and not to harm you, plans to give you hope and a future.’
=New International Version=

* Effective Introduction

your introduction should arouse interest, identify your subject and show why your listeners should be interested in it

** Arouse Interest
Select a question, real-life experience, or news item that will be of interest to you listeners.

give careful thought to the interests and concerns of you listener

** Identify the subject
make sure your subject and purpose is clear to your listeners

** Show why the subject is important.
they should understand how the subject can help them

* Meaning of Jeremiah 29:11

Jehovah God promised his worshipers that he had a peaceful future in mind for them.

Though written in the past, these words still reflect God's thoughts.

God had these things recorded so that we might have hope.
=Romans 15:4=

* Context of Jeremiah 29:11

These words were part of a letter sent to the Israelites in Babylon,
who were taken captive from Jerusalem. *Jeremiah 29:1*

in *Jeremiah 29:4-9*, he is telling them that they will be there for a long time and that
they should build homes, plant gardens, and raise families.

However lets read,  *Jeremiah 29:10*

it says that after 70 years god would turn his attention to them, and that is when *Jeremiah 29:11* comes in

God kept his promise.

the fulfilled promise of Jeremiah 29:11 assure those who hope in God's promises today.

* Misconception 1: God has a specific plan for each individual

fact God lets people choose for themselves

his words in Jeremiah 29:11 were addressed to a group.

* Misconception 2: God will prosper his worshipers

the word prosper is translated from the hebrew word that mean "peace,health and well-being"

according to the context God promissed his people that he would give them peace and wellfare.

* outline

** Tell me is you have heard this

god has a plan for you life.

A lot of people belive that God has a specific plan for every individual, from the moment they are born to the day they are dead.

some people might receive comfort from that idea.

** but then some people might begin to wonder.

if God has a plan for my life, if some bad happens to me, does that mean that God planed it?

if everything that is going to happen to me has already be writen, how do I have free will?

if God has this all encompassing plan and there is nothing that can be done to stop it?
Than what is the point to praying to him?
What do you want him to do? change the plan?

** This idea that God has a specific plan for each idividual contridicts two fundamental truths that we know about God
One that God is love.

Two that he has given us the gift of free will.

You can not say God is love and is never responsible for the evil we suffer in our lives and at the same time say God has a plan for your life.

You can not say God have given us free will and at the same time say
that everything that is going to happen to use and and every desition we are going to make was desided before we were even born.
that doesn't make any sence.

these are contridictions and God has no contradictions.


** Where did this idea come from?
- false religion
- philosophy
- misunderstanding of the scriptures and failing to consider there context.
  
  one in particular where we are going to focus on is Jeremiah 29:11
  
  In this talk we are going to really look close to what Jeremiah said and try to figure out it's real meaning.
  

** Let us read Jeremiah 29:11
=For I well know the thoughts that I am thinking toward you,’ declares Jehovah,
‘thoughts of peace, and not of calamity, to give you a future and a hope=
- notice how we use the word thoughts
- now i would like to read the new international version of 
 =‘I know the plans I have for you,’ declares the LORD,‘plans to prosper you and not to harm you,
  plans to give you hope and a future.=
  
  do you see how suttle difference in translation can potentially convey a completely different idea?
  so what is the correct interpretation?
   
** Friends if you get anything from this talk, remember this Context matters.

- so lets now read Jeremiah 29:1
  =These are the words of the letter that Jeremiah the prophet sent from Jerusalem to the rest of the elders among the exiled people,
  the priests, the prophets, and all the people, whom Neb·u·chad·nezʹzar had taken into exile from Jerusalem to Babylon,=

  These words were part of a letter sent to the Israelites in Babylon,
  who were taken captive by Babalon.

  this letter was adressed to a Group of people, not an individual.

  now lets look at Jeremiah 29:10.

** let look a Jeremiah 29:10
=“For this is what Jehovah says, ‘When 70 years at Babylon are fulfilled,
I will turn my attention to you, and I will make good my promise by bringing you back to this place.’j=

  now Jeremiah 29:11 lets Jeremiah 29:12 again
  
  Jehovah is not saying that he has an individual plan for everyone but that he giving hope to the Jews who are help captive in babalon.
  He is letting him know that he will not forget them and he will bring about his original purpose he had for them.

  do you see know how context can completly change the meaning of a scripture.
  
  it's not that translation from the new international version is wrong but if you dont' consider the context
  that scripture can take on a totaly different meaning.

** so what can we get from this.

I want to be very carful. I'm not saying that God does not think ahead or plan.
No doubt he has good things planed for all of us in the paradise to come.

but He also does not take away our free will.

this account was recorded not to show that God has a plan for us individually but to show God's faithfulness in carrying out his purpose for his people.

after the 70 years were over Jehovah brought his people back as he said he would.

If Jehovah came through for his people back then how much more should we expect him to fulfill  his Plans for his people now.

so when you hear someone say to you that God has a plan for your life. We can say we partially agree with that person but we also know that it is up to us if we are
going to go through that plan.

