:PROPERTIES:
:ID:       cdcfcd50-4a4b-457d-815b-bd72ca78f737
:END:
#+title: Reflecting on Jehovah's qualities builds faith
#+filetags: :treasures:

[[id:360543e2-053b-4a88-a7de-10a1868ede25][Treasures from god's word]]

* intro

brothers I would like to ask you to picture your self in Jerusalem months before it was destroy.
the Babylonians have surrounded the city and are battering it's walls.
food is short and people are exhausted.
at this point you don't have to believe in Jeremiah to see that it's only a matter of time before they get in.

during a time such as this is when Jehovah gives these instructions to Jeremiah.

Jeremiah 32:6-8
=Jeremiah said: “The word of Jehovah has come to me, saying,‘Here Hana·mel the son of Shallum your uncle* will come to you and say:=
=“Buy for yourself my field in Anaa·thoth,a because you have the first right to repurchase it.=
=Hanaa·mel the son of my uncle came to me, just as Jehovah had said, into the Courtyard of the Guard, and he said to me:=
=“Please buy my field in Anaa·thoth, in the land of Benjamin, for you have the right to take possession of it and to repurchase it.=
=Buy it for yourself.” At that I knew that this was by the word of Jehovah.=

could you imagine what might have been going on in Jeremiah's head?
you want me to invest in restate in a time like this?
but despite what ever confusion or concerns he may have had, Jeremiah's obeyed.

so why did God asked Jeremiah to buy that field?
Jeremiah already had faith that God would alow the Jews to return after 70 years have passed.
but Jehovah is reinforcing that faith by giving him something physical to help him think about the time when
people will start planting again, building again and raise families again.

friends it's never too late for you to buy a field in anothoth.

in [[id:843f6124-5bcf-4762-85c3-a6446320b23f][Hebrews_11:1]]

in the Simple English bible it says
=Faith is the title deed for good things to come.=

our faith is the deed that guarinties that we a special place waiting for us in paradice.

but how do we build our faith so that it's as real to use as holding a physical deed in our hands.

remember A deed is only as good as the ones who signs it.
if the person you entered the deed with will not honor it then all you have is a piece of paper.

but if you know the person you signed with is not only able but willing to honor their part of the agreement.
then you can literly take that to bank.

in the same way when we reflect on Jehovah's qualities we can begin to see that Jehovah is not just willing
but able to fullfill his part of the agreement.

in this talk we are going to see how reflecting on Jehovah's qualities can build our faith.
and we are going to do that by focus on three qualities, his powerm, his love and his justice.


* Lets first focus on his Power

tell me if you heard this phrase before, don't let your mouth write checks which you can't cash.

Jehovah has made some pretty large promise.
World Peace,
Restoring the earth into a paradise conditions.
Resurrecting the dead

That's a pretty tall order. do you think god is able to make good on his claims.
let's see what Jeremiah has to say.

[[id:5bbb91b4-878c-4d0b-8b0d-00efb6e4e4d2][Jeremiah 32:17]]

it says here nothing is too wonderful for you.

maybe you more convincing then reading something that was written over 2000 years ago.

if you need physical evidence look further evidence of Jehovah's power look no further than creation.


For example take the sun.
at it core, it temperature is 27,000,000 F or 15,000,000 C
every second it emits enery equivalent to hundres of million of atomic bombs.

yet our sun is small in comparison to many untold trillions of stars.
scientis estimate that one of the largest starts, named UY Scuti, has a diameter 1,700
times of the sun. If UY Scuti repaced the sun, it would engulf the earth and extend beyond
the orbit of jupiter.


Do you think the God can make good on his promises. 


* Jehovah's loyal love assures us that he wants to help us
so you might think we so what.
just because he is able doesn't mean he is willing?

[[id:1d9acea5-be01-4744-9829-f33b4dc902cb][Jeremiah 32:18]]

Before we began serving Jehovah, we received the love that God shows to man kind in a general sence.

but now as his worshipers we also benifit from his Loyal love.

move by that love Jehovah embraces us with his protetive arms.
he will always keep us close to him and fulfill his purpose regarding us.

we wants us to succedd

no matter what trial we face, jehovah will give us the strenght we need in order to keep our integrety.

* Jehovah's sense of justice reminds us that he sees injustice and will act against it

[[id:f34576ae-dffc-455a-8c43-0e117289ec41][Jeremiah 32:19]]

although Jeremiah expressed his frustration, he did not question God's justice.

As he was how Jehovah disciplined His rebellious people, his confidence in God's Justice must have increased

we too can openly express our frustrations in prayer, trusting that jehovah will in his due time correct any injustices we now face.

* conclusion

In conclusion friends by reflecting on 
