:PROPERTIES:
:ID:       cdcfcd50-4a4b-457d-815b-bd72ca78f737
:END:
#+title: Reflecting on Jehovah's qualities builds faith
#+filetags: :treasures:

[[id:360543e2-053b-4a88-a7de-10a1868ede25][Treasures from god's word]]

* intro

* Jehovah's power convinces us that he can help us

[[id:5bbb91b4-878c-4d0b-8b0d-00efb6e4e4d2][Jeremiah 32:17]]

Evidence of God's power is seen in creation.
For example the sun.
at it core, it temperature is 27,000,000 F or 15,000,000 C
every second it emits enery equivalent to hundres of million of atomic bombs.

yet our sun is small in comparison to many untold trillions of stars.
scientis estimate that one of the largest starts, named UY Scuti, has a diameter 1,700
times of the sun. If UY Scuti repaced the sun, it would engulf the earth and extend beyond
the orbit of jupiter.

and if that doesn't impress you consider this.

how do we benifit from God's power.
our life depends on God's pysical creation, which he brought about through his power
god uses his power to benifit humans
he did with jesus
he give power to the tired ones
god can give power beyond what is normal
do you not feel drawn to a God who uses his limitless power for our behalf.


he does it with ease, this is all lighter than a fether to him

* Jehovah's loyal love assures us that he wants to help us

[[id:1d9acea5-be01-4744-9829-f33b4dc902cb][Jeremiah 32:18]]

* Jehovah's sense of justice reminds us that he sees injustice and will act against it

[[id:f34576ae-dffc-455a-8c43-0e117289ec41][Jeremiah 32:19]]

* Family Worship IDEA: Watch Video Buy a field in Anathoth

Jeremiah 32:6-8

buy field in Anathoth

buy a field???

legal transaction, transparency and witnesses

certenti that jehovah will bring his people back

128 men of anothoth returned

faith is the assurce of what is hope for

faith is the title deed as to which we hope for will come true

our faith is a title deed of good things to come

Jeremiah has a title deed.

we have a title deed of faith

How do we buy a field in anathoth?
exersise faith in Jehovah's promises

faith is like a title deed of things hoped for

when you greving by a field in anathoth.


* conclusion
