#+title:      claude code
#+date:       [2026-09-02 Wed 09:08]
#+filetags:   :ai:anthropic:claude:
#+identifier: 20260902T090849

Agentic Coding Tool

has tools

AI thrives in good coded bases

AI needs feedback loops
typechecking
browser
tests


* tools
Read,Write,Bash

* terminal setup
~/terminal-setup~ : allows Shift + Enter for new line

* init
~/init~ : initialize a claude.md file

scans project

provide context to claude code

~#~ : to memorize command in claude.md 

* context

context for your session

~@path/to/file~ : you can add a file as context to claude code

~/clear~ : clear context

~/compact~ : compact the context and give it a summary


*press ESC twice* : rewide to previous point in context

* MCP

a way to add tools and resources to claude

allows claude code to communicate outside your code base

Model Context Protocol

communicates with a MCP server

ex: PlayRight

~claude mcp add context7 --scope project -- npx -y @upstash/context7-mcpclaude~

~claude mcp add playwright npx @playwright/mcp@latest~

~claude mcp add -s user playwright -- npm @playwright/mcp@latest~

~/mcp~ : show mcp servers

context7 : give modles updated information about frameworks

playright : allows claude to open browser, allow claude to see it.

* SKILLS

teaches claude how to do something once

the description helps claude deside when to use the skill

when ever you pass a promt to claude is compares to all the skill descriptons to see if it's appropriate to use it.

~.claude/skills~

ask claude to do certain things in a specific way

a reusable workflow

~SKILL.md~

~/<new-skill>~

give claude instructions on how to do things

you can lookup skills online

just prewriten instuctions instructing claude how to do a certain task

explain code standards to claude

skills is so you don't have to repeate yourself

claude compaire prompt to skill descriptions

~.claude/skills~

skills load on demand when they match your request

if you find yourself repeating to claude then that is a skill

you need to specify skill for subagents, they are not automatically loaded

you can specify which tools and model to use in a skill

try to keep your skill under 500 line.  if you cant then consider splitting it up.

#+begin_src markdown
  ---
  name: <name-of-skill>
  description: <descrition-of-skill>
  ---
  instructions
#+end_src
- description tell claude when to use it, matching criteria

skills are reusabel instructions

you can store reference and script in the folder.  they only get added to context when needed

SKILLS.md is the brain. the support files (script,references) are the tools.

a skill folder contains
- SKILL.md (instructions)
- scripts/ (executable code)
- references/ (documentation loaded as needed)
- assets/ (templates,fonts,icons used in output)

SOP (standard operating procedure)

Progressive Disclosure : load refrences and scripts as needed to context

we can setup skill that run custom scripts

frontend design skill???

agents need well defined processes

skills help stear your agents to keep them on the right track

define good triggers

** grill-me
helps you flesh out an idea

#+begin_src markdown
  ---
  name: grill-me
  description: Interview the user relentlessly about a plan or design untill reaching a shared understanding,
  resolve each branch of the decision tree.  Use when user wants to stress-test a plan,
  get grilled on their design, or mentions "grill me"
  ---

  Interview me relentlessly about every aspect of this plan untill we reach a shared understranding.
  Walk down each branch of the design tree, resolve dependencies between decisions one-by-one.

  If a question can be answered by exploring the codebase, explore the codebase intead.
#+end_src

relentlessly -> until we reach a shared understanding

decision tree -> one branch at a time

one at a time -> wait for my answers befor next

recommend one -> never hand me a blank question but also provide a recomendation

** to-spec
convert conversation you had from grill-me to a offical document or PRD(Product Release Document)

** to-tickets
converst what we have in spec to tickets that we can act on

don't group by layer but by feature

** implement
implement code
use /tdd where ever possible
use /code-review when done

** write-prd
Product Release Document

help you take your idea and create a document

** prd-to-issues
break down prd into task or github issues

** tdd
test driven development

** front-end-design
offical skill from anthropic
use real design principles

** /grill-with-docs

** /tdd-workflow

** /code-reviewer
use it to review PRs

** /skill-creator
it builds skills for you
claude interviews you till it creates the skill


** /review
claude does code review on what you just build
bugs
edge cases
design issues

** /to-spec

** /to-ticket

** /implement

** /code-review

gril-me -> to-spec -> to-tickets -> code-review -> implement



* Github

use Claude to review github pull requests

automatically work on issues

need github cli installed on your computer

~/install-github~ : setup claude Github Actions for repo

* tools

claude code comes with built in tools like Bash, Read, Edit, grep, LS,  WebSearch, WebFetch, etc ...

claude code knows when to use certain tools based on your instructions


* plan mode

Shift + Tab : cycle till you hit plan mode

* extended thinking

ask AI to think longer in implementing complex solutions

put /thing to tell claude to think harder???

* commands

a slash command to you can give to claude code

ex: create a component
give instructions on how you want the component to be made.

* subagents

create a team in a project

each subagent can be isolated and configured to work on a particular task

ex: Unit Tester, Security Auditor, UX Reviewer

- you can setup the UX Reviewer to use playright

claude code and delegate tasks to subagents

~/agents~ : start creating agents

a subagent is a cerperate claude session that gets spun up to handdle a task and reposts it back to the main thread
it has it's own context window

they are good for optimize your code

they run in their own context window so that the main context window does not get bogged down

use subagents if you want a seperate execution context

keep context window clean

~/agents~
you can create your own subagents

/Create a front-end engin3eer that is an expert in Next.js, Tailwind, etc/

a subagent is an agent that runs in a seperate context window

if your going to do a complex task it makes sense to hand it over to an agent so that it does not polute the context window

you can also delegate them to cheaper modles

you can use more specialized agent instead of One big general agent with context bloat

you need to specify what the agent does and when claude should use it

Sonnet is for executing
Opus is for planning

you can invoke a specific agent with @ in the prompt

it keeps you context clean

you can specify the model the agent should run

progresive disclosure, claude reads promt and desides if it needs to run it

you can make specialists
security-auditor
tester
doc-writer
db-expert
frontend-developer
backend-developer

awesome-claude-code-subagents

it you just need it to do one thing than keep it inline

if it's heavy an noisy and will fill context then use subagents

cheaper workers

better results, a fresh agent with a clean context

you make a prompt to claude and claude makes the desicion if it needs to delegate to a subagent or use a tool

~.claude/agent-memory~ : memory of the agent???

name:
description:
tools:
model:
memory: project // save to agent so that we don't have to rexplain
instuctions

ways to trigger sub-agenets
1. Natual Language
   Use the code-reviewer to check my changes
2. @mention
   tag the agent
3. session wide
   claude --agenet code-reviewer


use agents to keep your context clean

front end agent
back end agent
qa/tester
security
docs reviewer
code reviewer
designer

* agent teams

teams of agents can communicate with each other
allows colaboration between agents

it agents need to talk to each other

limitation to sub-agents they can only comnunicate with the main agent and not with each other

avoid context rote

letting sub-agents to talk to each other

shared task list

you need to enable them in claude code

delegates tasks to fresh claude instance

subagents cant talk to eachother

agent teams can talk to each other

good for parallelizable tasks

they tend to be a little slower and more expensive but better cuality

Goal: ....

create a team of 3 agents

1. ** Backend Dev **
2. ** Frontend Dev **
3. ** QA **

final deliverables:
-
-
-

no more than 3 - 5 agents

team mates can talk to eachother the don't need to go through the main agent

you can see each context from tmux

you have to explictly tell claude to create an agent team

agent split tmux for you

colaboration vs isolation

you need a terminal that support Split-pane mode, tmux

you need to explicity tell claude to create an agent team

subagent are more for a focused task not colaborative

* modles

select models

~Alt + p~ : switch modeles

* usage

see usage of tokens

* btw
you can ask a side question

* !
command mode, you can run a shell command in promtp

* Mode Switch
~Shift + Tab~ : switch mode

plan mode

auto mode

* context window

~/context~  :  see if your within your context limit

* resume

~/resume~ : resume previous session

* .agents/skills

universal for all AI frameworks

is where skills are saved

.claude/skill is a symbolic link


* AGENTS.md

claude.md can reference it

@agents.md

* Conversation History

every session you have is stored

~claude --resume~

* hook

auto instructions

steps that get triggered 

* worktree

you can tell claude to work in a work tree

--worktree

you can have agents work on seperate worktrees

* docker

~docker sandbox run claude~:  run claude code in sandbox

* sandbox

~/sandbox~: run claude in sandbox mode

* cheatsheet

[[denote:20260921T114237][claude-code-cli-settings-cheat-sheet]]

* Prompt and Context enginering

Specific instructions (prompt)
Relative information (context)

any task you want the AI to do starts with a promt

@file is a way to add context
